name: documentation_preview

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "md2conf/**"

jobs:
  create-preview:
    runs-on: ubuntu-latest
    name: Uploading Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        uses: TTengs/MarkdownToConfluence@v3
        with:
          fileslocation: 'md2conf'
          confluence_url: 'https://servicetitan.atlassian.net'
          confluence_space_key: 'BI'
          auth_username: ${{ secrets.CONFLUENCE_USERNAME }}
          auth_api_token: ${{ secrets.CONFLUENCE_API_TOKEN }}
          is_preview: false
